### ISSUE TITLE
eggjs与rabbitmq断开连接等待超时之后项目直接崩溃

### ISSUE THREAD

**Issue by ks4na** [fuxingZhang/egg-rabbitmq#3]
启动eggjs 项目后能够正常连接和使用 rabbitmq，然后断开二者的连接后，等待一段时间后超时报错，控制台可以看到报错 TIMEOUT，虽然控制台报错了没有退出，但是此时程序已经无法提供服务了， curl 请求服务就直接报错 ECONNREFUSED。

是 error 等事件没有监听导致的吗？

**Comment by fuxingZhang** [comment]
我已经很多年不做JS相关开发，你可以fork项目，自行维护
